name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/github/zregvart
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build and run tests
        run: ./mvnw --no-transfer-progress verify
      - name: Test annotations
        run: |
          echo "::error file=io/github/zregvart/junit/github/FailingTest.java,line=1,col=0::FAILED - package + class.java"
          echo "::error file=FailingTest.java,line=2,col=0::FAILED - class.java"
